#!/bin/sh
#
# An example hook script to check the commit log message.
# Called by "git commit" with one argument, the name of the file
# that has the commit message.  The hook should exit with non-zero
# status after issuing an appropriate message if it wants to stop the
# commit.  The hook is allowed to edit the commit message file.
#
# To enable this hook, rename this file to "commit-msg".

# Uncomment the below to add a Signed-off-by line to the message.
# Doing this in a hook is a bad idea in general, but the prepare-commit-msg
# hook is more suited to it.

# Get the commit message
commit_msg=$(cat $1)

# Define the commit message format regex
commit_regex='^(feat|fix|docs|style|refactor|test|chore)(\([a-zA-Z]+\))?: .{1,50}$'

# Check if the commit message matches the regex
if ! [[ $commit_msg =~ $commit_regex ]]; then
    echo "Invalid commit message format. Commit message should follow: <type>[optional scope]: <description>"
    exit 1
fi