name: Prod deployment from Github to AWS Elastic Beanstalk
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest # the OS your job should run on
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout Latest Repo
        uses: actions/checkout@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: kevindocker123/unit-conversion-ui:latest

      - name: Generate Deployment Package
        # zip all files except .git
        run: zip -r deploy.zip * -x "**.git**"

      - name: Get timestamp
        uses: gerred/actions/current-time@master
        id: current-time

      - name: Run string replace
        uses: frabert/replace-string-action@master
        id: format-time
        with:
          # replaces '[:\.]+' in the timestamp with '-'
          pattern: '[:\.]+'
          string: '${{ steps.current-time.outputs.time }}'
          replace-with: '-'
          flags: 'g'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: UnitConversionUI
          environment_name: UnitConversionUI-env
          version_label: 'docker-appUI-${{ steps.format-time.outputs.replaced }}'
          region: us-east-1
          deployment_package: deploy.zip
